In [28]:
import numpy as np

a = np.array([10, 20, 30])
print(a*20)

[200 400 600]


In [2]:
#slicing and indexing
import numpy as np
a = np.array([10, 20, 30])
print(a[0:2])

[10 20]


In [13]:
b_arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(b_arr[0])
print(b_arr[0, 0])
print(b_arr[0, :2])
print(b_arr[0:2])
print(b_arr[0:2, 0:2])
print(b_arr[0:2, 0:3]) # we can't define diff. lenth

[10 20 30 40]
10
[10 20]
[[10 20 30 40]
 [50 60 70 80]]
[[10 20]
 [50 60]]
[[10 20 30]
 [50 60 70]]


In [16]:
c_arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [20, 40, 60, 80]])
print(c_arr[2,2:])

[60 80]


Attributes:
Shape:-
    It returns the shape of the array in terms of '(row, column)'.

size:-
    It returns the no. of elements present inside the array.

ndim:-
    It returns the dimension of the array.

dtype:-
    It returns the datatype of the elements that the array consists of.
    
len:-
    It returns the no. of nested values inside the array.

astype:-
    It converts an array to different type.

type:-
    It returns the datatype of the variable.

In [30]:
# Example

arr1 = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [20, 40, 60, 80]])
print(np.shape(arr1))
print(np.size(arr1))
print(np.ndim(arr1))
print(arr1.dtype)
print(len(arr1))
print(arr1.astype(str))
print(type(arr1))

(3, 4)
12
2
int32
3
[['10' '20' '30' '40']
 ['50' '60' '70' '80']
 ['20' '40' '60' '80']]
<class 'numpy.ndarray'>


Mathematical Operations and Functions:

add():-
    It adds one array with another array or any value.
sustract():-
    It substracts one array from another array or any value.
multiply():-
    It multiplys one array with another array or any value.
div:-
    It divides an array by another array or any value.
pow():-
    It returns the power(s) of an array.
sqrt():-
    It returns the square root of elements of an array.

In [10]:
# Exapmple with 1D array

a1 = np.array([1, 2, 3, 5])
a2 = np.array([7, 3, 1, 4])

print(np.add(a1, a2))
print(np.subtract(a1, a2))
print(np.multiply(a1, a2))
print(np.divide(a1, a2))
print(np.power(a1, a2))
print(np.sqrt(a1))


[8 5 4 9]
[-6 -1  2  1]
[ 7  6  3 20]
[0.14285714 0.66666667 3.         1.25      ]
[  1   8   3 625]
[1.         1.41421356 1.73205081 2.23606798]


In [9]:
# Exapmple with 2D array
a3 = np.array([[1, 3, 6], [2, 1, 3]])
a4 = np.array([[3, 2, 1], [1, 5, 3]])

print(np.add(a3, a4))
print(np.subtract(a3, a4))
print(np.multiply(a3, a4))
print(np.divide(a3, a4))
print(np.power(a3, a4))
print(np.sqrt(a3))

[[4 5 7]
 [3 6 6]]
[[-2  1  5]
 [ 1 -4  0]]
[[3 6 6]
 [2 5 9]]
[[0.33333333 1.5        6.        ]
 [2.         0.2        1.        ]]
[[ 1  9  6]
 [ 2  1 27]]
[[1.         1.73205081 2.44948974]
 [1.41421356 1.         1.73205081]]


Combining and splitting arrays:

concatenate:-
    It return an array by concatenating multiple arrays (horizontal/vertical).
    by defaule it concates horizontally.
hstack:-
    It concats horizontally.
vstack:-
    It concats vertically.
    

In [16]:
#  Example with 1D array

a5 = np.array([1, 2, 3, 5])
a6 = np.array([7, 3, 1, 4])

print(np.concatenate([a5,a6]))
print(np.hstack([a5,a6]))
print(np.vstack([a5,a6]))

[1 2 3 5 7 3 1 4]
[1 2 3 5 7 3 1 4]
[[1 2 3 5]
 [7 3 1 4]]


In [24]:
#  Example with 2D array

a7 = np.array([[1, 3, 6], [2, 1, 3]])
a8 = np.array([[3, 2, 1], [1, 5, 3]])

print(np.concatenate([a7,a8]))
print(np.concatenate([a7,a8], axis=1))
print(np.hstack([a7,a8]))
print(np.vstack([a7, a8]))

[[1 3 6]
 [2 1 3]
 [3 2 1]
 [1 5 3]]
[[1 3 6 3 2 1]
 [2 1 3 1 5 3]]
[[1 3 6 3 2 1]
 [2 1 3 1 5 3]]
[[1 3 6]
 [2 1 3]
 [3 2 1]
 [1 5 3]]


Array split:-
    To split an array into multiple parts, 'array_split()' is used.

In [28]:
a9 = np.array([1,2,3,4,5,6,7,8,9,10])
a10 = np.array_split(a9,3)
a11 = np.array_split(a9,6)
print(a10)
print(a11)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10])]
